language: c

before_install:
- git clone https://github.com/OpenXT/v4v.git
- sudo cp v4v/v4v/linux/v4v_dev.h /usr/include/linux/
- sudo cp -r v4v/v4v/include/xen /usr/include/
- cd v4v/libv4v
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd -

install:
- sudo apt-get update
- sudo apt-get install build-essential libusb-dev libdbus-1-dev libdbus-glib-1-dev libudev-dev libxenstore3.0

before_script:
- ./autogen.sh
